# Generated by Django 3.1.7 on 2022-04-27 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('cardinal', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('author_id', models.CharField(blank=True, max_length=20)),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quote_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reply_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('retweet_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('text', models.CharField(max_length=280)),
                ('polarity', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_tweets.data')),
            ],
        ),
    ]
