# Generated by Django 3.1.7 on 2022-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
